### PR TITLE
Set JSONEncoder to json._default

### LINKED ISSUE #528: AttributeError: module 'quart.json' has no attribute 'JSONEncoder'
Bump into this error when I run `pipenv run hypercorn --reload --quic-bind 0.0.0.0:4433 --certfile server.crt --keyfile server.key --bind 0.0.0.0:8080 src.main:app`:
```
<snip>
  File "/usr/src/PythonRestAPI/src/main.py", line 5, in <module>
    from flask_wtf.csrf import CSRFProtect, CSRFError
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-JI5RzKtM/lib/python3.10/site-packages/flask_wtf/__init__.py", line 4, in <module>
    from .recaptcha import Recaptcha
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-JI5RzKtM/lib/python3.10/site-packages/flask_wtf/recaptcha/__init__.py", line 1, in <module>
    from .fields import RecaptchaField
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-JI5RzKtM/lib/python3.10/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-JI5RzKtM/lib/python3.10/site-packages/flask_wtf/recaptcha/widgets.py", line 6, in <module>
    JSONEncoder = json.JSONEncoder
AttributeError: module 'quart.json' has no attribute 'JSONEncoder'
```

Environment:

- Python version: 3.10.4
- Flask-WTF version: 1.0.1
- Flask version: 2.1.3
https://github.com/pallets/quart/issues/163

### PR DESCRIPTION
**Pull request by pythops**
- fixes #528 

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `docs/changes.rst` summarizing the change and linking to the issue. Add `.. versionchanged::` entries in any relevant code docs.

### CODE REVIEW

**Comment by pythops** [comment]
@azmeuk 
can you please take a look at that one. this is blocking to use the latest version of Quart

**Comment by azmeuk** [comment]
It looks like `JSONEncoder` is not even used anymore. It was introduced with 6dea39dd2f130571c0028f1de6e489260fa01d47 and was not called anymore with 92c6e3953c3bdf2ff3cf03c1216648e6e0b77a0a.
I think you can just remove the line.

**Comment by pythops** [comment]
even better ! okay, I'll remove the line
